language: php

php:
  - 5.6
  - hhvm

matrix:
  allow_failures:
      - php: hhvm

before_install:
  - composer self-update

install:
  - composer self-update
  - composer update

script:
  - vendor/bin/tester -p $TESTER_PHP_BIN $TESTER_ARGS tests/

after_failure:
  # Prints *.actual files content
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

after_success:
  - composer require satooshi/php-coveralls:0.*
  - vendor/bin/coveralls -v
  - sudo pip install --upgrade pip
  - sudo pip install -q sphinx
  - sudo pip install sphinx-better-theme
  - cd docs/
  - make html
  - git config --global user.email "worker@travis-ci.org"
  - git config --global user.name "Travis Ci Worker"
  - make ghpages

env:
  matrix:
    - TESTER_PHP_BIN=php-cgi TESTER_ARGS="-c tests/php.ini --coverage build/logs/clover.xml --coverage-src library/"
    - TESTER_PHP_BIN=hhvm TESTER_ARGS=""
  global:
    - GH_REF=github.com/webino/Webino
    - secure: Jzh/BiLKUvPNvubiQtMyjuCoofu+I3n5DeeXTMlkG7rcd8Kq3T3izdt25PFX8nJ+eJZev1HsiXWlPludGWyYXniQ+k7EqI8BxlyZdervt1ElofsuKskvo1/4yYw9ZetNDLWV8fWNKDuNvoEuiJXI5Xq2np8nlarsYLiNAJVKv9M=
