language: php

php:
  - 5.6
  - hhvm

install:
  - composer self-update
  - composer update

script:
  - vendor/bin/tester -p php -c tests/php.ini --coverage build/logs/clover.xml --coverage-src library tests/

after_success:
  - composer require satooshi/php-coveralls:0.*
  - vendor/bin/coveralls -v
  - sudo pip install --upgrade pip
  - sudo pip install -q sphinx
  - sudo pip install sphinx-better-theme
  - cd docs/
  - make html
  - git config --global user.email "worker@travis-ci.org"
  - git config --global user.name "Travis Ci Worker"
  - make ghpages

env:
  global:
    - GH_REF=github.com/webino/Webino
    - secure: Jzh/BiLKUvPNvubiQtMyjuCoofu+I3n5DeeXTMlkG7rcd8Kq3T3izdt25PFX8nJ+eJZev1HsiXWlPludGWyYXniQ+k7EqI8BxlyZdervt1ElofsuKskvo1/4yYw9ZetNDLWV8fWNKDuNvoEuiJXI5Xq2np8nlarsYLiNAJVKv9M=
