language: php

php:
  - 7.1
  - hhvm

before_install:
  - composer self-update

install:
  - composer self-update
  - composer update

script:
  - vendor/bin/tester -p $TESTER_PHP_BIN $TESTER_ARGS tests/

after_failure:
  # Prints *.actual files content
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

after_success:
  - composer require satooshi/php-coveralls:0.*
  - vendor/bin/coveralls -v
  - sudo pip install --upgrade pip
  - sudo pip install -q sphinx
  - sudo pip install sphinx-better-theme
  - cd docs/
  - make html
  - git config --global user.email "worker@travis-ci.org"
  - git config --global user.name "Travis Ci Worker"
  - make ghpages

matrix:
  allow_failures:
    - php: hhvm
  exclude:
    - php: 7.1
      env: TESTER_PHP_BIN=hhvm TESTER_ARGS=""

    - php: 7.1
      env: TESTER_PHP_BIN=php-cgi TESTER_ARGS="-c tests/php.ini --coverage build/logs/clover.xml --coverage-src library/"

    - php: hhvm
      env: TESTER_PHP_BIN=php-cgi TESTER_ARGS="-c tests/php.ini --coverage build/logs/clover.xml --coverage-src library/"

    - php: hhvm
      env: TESTER_PHP_BIN=php-cgi TESTER_ARGS=""

env:
  matrix:
    - TESTER_PHP_BIN=php-cgi TESTER_ARGS="-c tests/php.ini --coverage build/logs/clover.xml --coverage-src library/"
    - TESTER_PHP_BIN=php-cgi TESTER_ARGS=""
    - TESTER_PHP_BIN=hhvm TESTER_ARGS=""
  global:
    - GH_REF=github.com/webino/Webino
    - secure: UOB4OJzFP4Qg1JWsmMEUEwKLn4eY6TqZbvYWAlXj85Q02pnvlzOHlyk2KyJQ4gVtw1b+atovuLYP1z3GhFAtdZCkv8wmHk0Sn8Htzia48InbJCU5AzbVUl44+R5o08NngFNKqGcGsuefU1GvljiuOdZJZ42oFmswK3V9TzbASlw=
