language: php

php:
- 5.6

install:
- composer self-update
- composer update

script:
- vendor/bin/tester -p php -c tests/php.ini --coverage build/logs/clover.xml --coverage-src library tests/

after_success:
- composer require satooshi/php-coveralls:0.*
- vendor/bin/coveralls -v
