<?php require __DIR__ . '/layout.php' ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Learn Webino — Webino 0.1.0alpha documentation</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="stylesheet" href="<?= $baseUrl ?>better.css" type="text/css">
    <link rel="stylesheet" href="<?= $baseUrl ?>pygments.css" type="text/css">
    <link rel="stylesheet" href="<?= $baseUrl ?>common.css" type="text/css">

    <link rel="top" title="Webino 0.1.0alpha documentation" href="#">
    <link rel="next" title="Installation" href="installation.html">

    <script type="text/javascript" src="<?= $baseUrl ?>jquery.js"></script>
    <script type="text/javascript" src="<?= $baseUrl ?>underscore.js"></script>
    <script type="text/javascript" src="<?= $baseUrl ?>doctools.js"></script>

    <link rel="stylesheet"
          href="//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700&amp;subset=latin,latin-ext"
          type="text/css">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Code+Pro:400,700&amp;subset=latin,latin-ext"
          type="text/css">
</head>
<body>
<div class="related top">
    <nav id="rellinks">
        <ul>
            <li>
                <a href="installation.html" title="Next document">Installation</a>
                →
            </li>
        </ul>
    </nav>
    <nav id="breadcrumbs">
        <ul>
            <li><a href="#">Webino 0.1.0alpha documentation</a></li>
        </ul>
    </nav>
</div>

<div class="document">
    <div class="documentwrapper">
        <div class="bodywrapper">
            <div class="body" role="main">
                <?= $content ?>
            </div>
        </div>
    </div>
    <div class="sidebar" role="navigation" aria-label="main navigation">
        <div class="sidebarwrapper">
            <p class="logo">
                <a href="<?= $baseUrl ?>">
                    <img class="logo" src="<?= $baseUrl ?>webino.png" alt="Logo">
                </a>
            </p>
            <menu>
                <?= $menu ?>
            </menu>
        </div>
    </div>
    <div class="clearer"></div>
</div>
<div class="related bottom">
    <nav id="rellinks">
        <ul>
            <li>
                <a href="installation.html" title="Next document">Installation</a>
                →
            </li>
        </ul>
    </nav>
    <nav id="breadcrumbs">
        <ul>
            <li><a href="#">Webino 0.1.0alpha documentation</a></li>
        </ul>
    </nav>
</div>
<footer id="pagefooter">© <?= date('Y') ?>, Webino, s. r. o. All rights reserved.</footer>
</body>
</html>
